# Generated by Django 3.2.18 on 2023-04-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_comment_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_author',
            field=models.CharField(max_length=255),
        ),
    ]
