# Generated by Django 3.2.18 on 2023-03-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_ingridiets',
            new_name='recipe_ingridients',
        ),
    ]
