# Generated by Django 3.2.18 on 2023-03-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_recipe_ingridiets_recipe_recipe_ingridients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='featured_comment',
            field=models.CharField(default='Shemmylicious Food', max_length=100),
        ),
    ]
