# Generated by Django 3.2.18 on 2023-03-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_comment',
            field=models.TextField(default='Shemmylicious Food'),
        ),
    ]
