# Generated by Django 3.2.18 on 2023-03-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_recipe_featured_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=models.FileField(upload_to='Shemmylicious'),
        ),
    ]
