# Generated by Django 3.2.18 on 2023-04-03 07:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230403_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='recipe', max_length=255, verbose_name='image'),
        ),
    ]
