# Generated by Django 3.2.18 on 2023-04-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230403_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_author',
            field=models.TextField(default='author'),
            preserve_default=False,
        ),
    ]
