# Generated by Django 3.2.18 on 2023-04-10 07:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='cat_recipe', max_length=255, verbose_name='image'),
        ),
    ]
