# Generated by Django 3.2.18 on 2023-04-10 08:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_category_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
