# Generated by Django 3.2.18 on 2023-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20230412_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='f_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/recipe/'),
        ),
    ]
