# Generated by Django 3.2.18 on 2023-04-12 10:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_recipe_f_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='f_image',
        ),
        migrations.AlterField(
            model_name='category',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='cat_recipe', max_length=255, verbose_name='image'),
        ),
    ]
