# Generated by Django 3.2.18 on 2023-04-12 16:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20230412_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='cat_recipe', max_length=255, verbose_name='cat image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='profile_img', max_length=255, verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='recipe', max_length=255, verbose_name='recipe image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
