# Generated by Django 3.2.18 on 2023-04-23 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0023_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_author',
            field=models.CharField(max_length=255),
        ),
    ]
